language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - "4"
  - "8"
  - "node"
script:
  - yarn lint:main
  - yarn test:coverage --no-cache
after_success:
  - "coveralls < coverage/lcov.info"
jobs:
  include:
    - stage: "umd"
      dist: trusty
      node_js: "node"
      script:
        - yarn lint:test-umd
        - yarn test:umd
      after_success:
        # no need to report coverage after UMD test
