language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - "4"
  - "6"
  - "node"
script:
  - yarn lint:main
  - yarn test
after_success:
  - "nyc report --reporter=text-lcov | coveralls"
jobs:
  include:
    - stage: "umd"
      dist: trusty
      node_js: "node"
      script:
        - yarn lint:test-umd
        - yarn test:umd
      after_success:
        # no need to report coverage after UMD test
