language: node_js
cache:
  directories:
    - ~/.npm
    - ~/.cache
node_js:
  - '10'
  - 'node'
install:
  - yarn install --frozen-lockfile
script:
  - yarn lint
  - yarn test:coverage --no-cache
  - yarn test:browser:ci
after_success:
  - 'coveralls < coverage/lcov.info'
